version: '2'
services:

    app_db:
      image: postgres:9.6
      environment:
        - POSTGRES_DB=app_db
        - POSTGRES_HOST_AUTH_METHOD=trust
      ports:
        - "54320:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    anal_db:
      image: postgres:9.6
      environment:
        - POSTGRES_DB=anal_db
        - POSTGRES_HOST_AUTH_METHOD=trust
      ports:
        - "54321:5432"